services:
  - type: web
    name: markr
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: dist/markr/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html